### ISSUE TITLE
Feature request: change rsync to straight copy when copying from lustre

### ISSUE THREAD

**Issue by yupinghuang** [ovro-eovsa/ovro-lwa-solar-ops#25]
There's very little need for rsync when getting data from lustre. It might be faster to just `cp -r` or use `copytree` under `shutil`.

**Comment by binchensun** [comment]
Good idea. Addressed in https://github.com/ovro-eovsa/ovro-lwa-solar-ops/pull/30. If the processing is done on the local server, download_msfiles() now uses cp instead of rsync. @yupinghuang
