### ISSUE TITLE
zombie processes?

### ISSUE THREAD

**Issue by yupinghuang** [ovro-eovsa/ovro-lwa-solar-ops#48]
At Jul 31 9PM pacific, `top -u solarpipe` on lwacalim00 ordered by memory usage looks like

<img width="628" alt="Screenshot 2024-07-31 at 9 05 55 PM" src="https://github.com/user-attachments/assets/f4ae0414-4a09-4b98-a748-f515c3652bc4">

Note the top few processes using up to ~15% of the RAM. They don't seem to be sleeping? `ps aux | grep` on one of them shows 

```
solarpi+ 1622368  0.0  5.7 32295044 30598096 ?   Ssl  Jul28   4:33 python /opt/devel/bin.chen/software/ovro-lwa-solar-ops/solar_realtime_pipeline.py --briggs -1.0 --slowfast slow --interval 600 --delay 240 --save_allsky
```

I don't know if this was intended? If I recall correctly, the solar pipeline doesn't have running processes when the Sun is not up?Same thing on other nodes, where they seems to be inactive processes using ~15% of RAM.

If this is unintended, it might be easier to ask the main process to terminate (or send a SIGTERM to it) past a certain time?

**Comment by binchensun** [comment]
Thank you for noticing that! These are indeed zombie processes that went dead. We'll find a way to kill them.

**Comment by binchensun** [comment]
By default, the pipeline, run by a cronjob, is supposed to end each day after sunset (see https://github.com/binchensun/ovro-lwa-solar-ops/blob/main/solar_realtime_pipeline.py#L1541), unless it is started manually to re-run some of the failed imaging or periods that require higher time resolution. However, the pipeline is ended by breaking off a loop. Therefore, dead processes (for whatever reason) are not automatically terminated. Here are some zombie processes on lwacalim01 showing that some are >1 week old. We need to terminate the main process after the pipeline is ended, as Yuping suggested. 
<img width="1552" alt="image" src="https://github.com/user-attachments/assets/b5e13412-f8d0-46c4-b158-893103c6d872">

**Comment by surajit4444mondal** [comment]
Closing this issue, as it has been fixed.
