### ISSUE TITLE
Compress fits files generated by realtime pipeline

### ISSUE THREAD

**Issue by binchensun** [ovro-eovsa/ovro-lwa-solar-ops#9]
suncasa.io.ndfits is used to wrap the individual FITS files into a single one. See
- https://github.com/ovro-eovsa/ovro-lwa-solar-ops/blob/main/solar_realtime_pipeline.py#L698
- https://github.com/ovro-eovsa/ovro-lwa-solar-ops/blob/main/solar_realtime_pipeline.py#L710

@sageyu123 mentioned that a newer Astropy version allows compression for 4-D FITS files. Updates to the suncasa requirement may be needed. This could be a suncasa issue as well.

**Comment by sageyu123** [comment]
Implementing compression for 4-D FITS files necessitates Astropy 5.3, which mandates Python >3.9. Prior to adoption, we'll conduct thorough testing to ensure compatibility and stability. In the interim, we will continue with 3-D FITS file compression.

**Comment by surajit4444mondal** [comment]
I think we have completed this. Hence closing this issue.
